// Code generated by emitter-gen. DO NOT EDIT.

package example

import (
	"github.com/pseudofunctor-ai/go-emitter/emitter/types"
)

var EmitterCallSites = map[string]types.CallSiteDetails{
	"active_users": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   34,
		FuncName: "",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"audit_log": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   46,
		FuncName: "",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"auth_failure_log": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   80,
		FuncName: "github.com/pseudofunctor-ai/go-emitter/testdata/example.IndirectlyDecoratedFunctions",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"cache_hit_metric": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   77,
		FuncName: "github.com/pseudofunctor-ai/go-emitter/testdata/example.IndirectlyDecoratedFunctions",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"decorated_log": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   59,
		FuncName: "",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"decorated_metric": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   58,
		FuncName: "",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"direct_count": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   21,
		FuncName: "github.com/pseudofunctor-ai/go-emitter/testdata/example.DirectCalls",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"direct_debugf_log": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   27,
		FuncName: "github.com/pseudofunctor-ai/go-emitter/testdata/example.DirectCalls",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"direct_error_log": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   26,
		FuncName: "github.com/pseudofunctor-ai/go-emitter/testdata/example.DirectCalls",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"direct_gauge": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   22,
		FuncName: "github.com/pseudofunctor-ai/go-emitter/testdata/example.DirectCalls",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"direct_info_log": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   25,
		FuncName: "github.com/pseudofunctor-ai/go-emitter/testdata/example.DirectCalls",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"error_log": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   47,
		FuncName: "",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"request_duration": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   33,
		FuncName: "",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
	"user_login_metric": {
		Filename: "/home/jamie/git/pseudofunctor-ai/go-emitter/testdata/example/example.go",
		LineNo:   32,
		FuncName: "",
		Package:  "github.com/pseudofunctor-ai/go-emitter/testdata/example",
	},
}

